package Corba;

/**
* Corba/CORBA_FalaeHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CORBA_module.idl
* Sábado, 28 de Maio de 2016 21h38min00s BRT
*/

public final class CORBA_FalaeHolder implements org.omg.CORBA.portable.Streamable
{
  public Corba.CORBA_Falae value = null;

  public CORBA_FalaeHolder ()
  {
  }

  public CORBA_FalaeHolder (Corba.CORBA_Falae initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Corba.CORBA_FalaeHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Corba.CORBA_FalaeHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Corba.CORBA_FalaeHelper.type ();
  }

}
